import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const NAVBARLINKS = [
    {
        name: 'Home',
        link: '/',
        children: []
    },
    {
        name: 'Services',
        link: '/services',
        children: []
    },
    {
        name: 'Portfolio',
        link: '/portfolio',
        children: []
    },
    {
        name: 'About Us',
        link: '/about',
        children: []
    },
    {
        name: 'Contact',
        link: '/contact',
        children: []
    },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="w-full h-20 bg-gradient-to-r from-dark via-white to-dark bg-dark flex justify-between items-center px-10">
          <div>
            <h2 className="text-2xl font-medium py-3 text-white">
                AUSTRIO-TECH
              </h2>
          </div>
          <div className="flex items-center space-x-4 text-lg font-medium">
            {NAVBARLINKS.map((row, index) => (
              <div key={index} className="text-white hover:text-primary">
                <Link href={row.link}>
                  {row.name}
                </Link>
              </div>
            ))}
          </div>
        </div>
        <div>
          {children}
        </div>
      </body>
    </html>
  );
}
